// GENERATED by tofino/exp-hash/gen_crcpoly.py from dpdk-nfs/lib/util/crc32.h -- do not edit.
// Which software CRC does each CRCPolynomial configuration of the bank compute? The built-in CRC32
// plus every bank entry hash {ipv4.src, tcp.dport}; the 32-bit results and two 10-bit truncations
// are appended to the packet, which loops back to its ingress port. See README.md.
#include <core.p4>
#include <t2na.p4>
header ethernet_h { bit<48> dst; bit<48> src; bit<16> etype; }
header ipv4_h { bit<8> vihl; bit<8> tos; bit<16> len; bit<16> id; bit<16> frag; bit<8> ttl; bit<8> proto; bit<16> csum; bit<32> src; bit<32> dst; }
header tcp_h { bit<16> sport; bit<16> dport; bit<32> seq; bit<16> data3; bit<16> win; }
header out_h { bit<32> h0; bit<32> h1; bit<32> h2; bit<32> h3; bit<32> h4; bit<32> h5; bit<32> h6; bit<32> h7; bit<32> h8; bit<32> h9; bit<32> h10; bit<32> h11; bit<32> h12; bit<32> h13; bit<32> h14; bit<32> h15; bit<32> h16; bit<16> t0; bit<16> t1; }
struct headers_t { ethernet_h eth; ipv4_h ipv4; tcp_h tcp; out_h o; }
struct meta_t { }
parser IgParser(packet_in pkt, out headers_t hdr, out meta_t meta, out ingress_intrinsic_metadata_t ig_intr_md) {
  state start { pkt.extract(ig_intr_md); pkt.advance(PORT_METADATA_SIZE); pkt.extract(hdr.eth); pkt.extract(hdr.ipv4); pkt.extract(hdr.tcp); transition accept; }
}
control IgDeparser(packet_out pkt, inout headers_t hdr, in meta_t meta, in ingress_intrinsic_metadata_for_deparser_t ig_dprsr_md) { apply { pkt.emit(hdr); } }
control Ig(inout headers_t hdr, inout meta_t meta, in ingress_intrinsic_metadata_t ig_intr_md, in ingress_intrinsic_metadata_from_parser_t ig_prsr_md,
           inout ingress_intrinsic_metadata_for_deparser_t ig_dprsr_md, inout ingress_intrinsic_metadata_for_tm_t ig_tm_md) {
  // coeff, reversed, msb, extended, init, xor
  CRCPolynomial<bit<32>>(0x04C11DB7, true, false, false, 0xFFFFFFFF, 0xFFFFFFFF) p_ieee;
  CRCPolynomial<bit<32>>(0x7B17A39F, true, false, false, 0xFFFFFFFF, 0xFFFFFFFF) p_p1;
  CRCPolynomial<bit<32>>(0x99F29AAD, true, false, false, 0xFFFFFFFF, 0xFFFFFFFF) p_p2;
  CRCPolynomial<bit<32>>(0x21BCA2C3, true, false, false, 0xFFFFFFFF, 0xFFFFFFFF) p_p3;
  CRCPolynomial<bit<32>>(0x0C596849, true, false, false, 0xFFFFFFFF, 0xFFFFFFFF) p_p4;
  CRCPolynomial<bit<32>>(0x3553D717, true, false, false, 0xFFFFFFFF, 0xFFFFFFFF) p_p5;
  CRCPolynomial<bit<32>>(0xAA1BC1D3, true, false, false, 0xFFFFFFFF, 0xFFFFFFFF) p_p6;
  CRCPolynomial<bit<32>>(0x297D4A93, true, false, false, 0xFFFFFFFF, 0xFFFFFFFF) p_p7;
  CRCPolynomial<bit<32>>(0xDE10F91F, true, false, false, 0xFFFFFFFF, 0xFFFFFFFF) p_p8;
  CRCPolynomial<bit<32>>(0xDC077BC9, true, false, false, 0xFFFFFFFF, 0xFFFFFFFF) p_p9;
  CRCPolynomial<bit<32>>(0xB5405445, true, false, false, 0xFFFFFFFF, 0xFFFFFFFF) p_p10;
  CRCPolynomial<bit<32>>(0x391E2DDD, true, false, false, 0xFFFFFFFF, 0xFFFFFFFF) p_p11;
  CRCPolynomial<bit<32>>(0x4E5ACD6D, true, false, false, 0xFFFFFFFF, 0xFFFFFFFF) p_p12;
  CRCPolynomial<bit<32>>(0x6AEEFABD, true, false, false, 0xFFFFFFFF, 0xFFFFFFFF) p_p13;
  CRCPolynomial<bit<32>>(0xFAF778B9, true, false, false, 0xFFFFFFFF, 0xFFFFFFFF) p_p14;
  CRCPolynomial<bit<32>>(0x99DFB91B, true, false, false, 0xFFFFFFFF, 0xFFFFFFFF) p_p15;
  Hash<bit<32>>(HashAlgorithm_t.CRC32) h_builtin;
  Hash<bit<32>>(HashAlgorithm_t.CUSTOM, p_ieee) h_ieee;
  Hash<bit<32>>(HashAlgorithm_t.CUSTOM, p_p1) h_p1;
  Hash<bit<32>>(HashAlgorithm_t.CUSTOM, p_p2) h_p2;
  Hash<bit<32>>(HashAlgorithm_t.CUSTOM, p_p3) h_p3;
  Hash<bit<32>>(HashAlgorithm_t.CUSTOM, p_p4) h_p4;
  Hash<bit<32>>(HashAlgorithm_t.CUSTOM, p_p5) h_p5;
  Hash<bit<32>>(HashAlgorithm_t.CUSTOM, p_p6) h_p6;
  Hash<bit<32>>(HashAlgorithm_t.CUSTOM, p_p7) h_p7;
  Hash<bit<32>>(HashAlgorithm_t.CUSTOM, p_p8) h_p8;
  Hash<bit<32>>(HashAlgorithm_t.CUSTOM, p_p9) h_p9;
  Hash<bit<32>>(HashAlgorithm_t.CUSTOM, p_p10) h_p10;
  Hash<bit<32>>(HashAlgorithm_t.CUSTOM, p_p11) h_p11;
  Hash<bit<32>>(HashAlgorithm_t.CUSTOM, p_p12) h_p12;
  Hash<bit<32>>(HashAlgorithm_t.CUSTOM, p_p13) h_p13;
  Hash<bit<32>>(HashAlgorithm_t.CUSTOM, p_p14) h_p14;
  Hash<bit<32>>(HashAlgorithm_t.CUSTOM, p_p15) h_p15;
  Hash<bit<10>>(HashAlgorithm_t.CUSTOM, p_ieee) h_t0;
  Hash<bit<10>>(HashAlgorithm_t.CUSTOM, p_p1) h_t1;
  action a0() { hdr.o.setValid(); hdr.o.h0 = h_builtin.get({hdr.ipv4.src, hdr.tcp.dport}); }
  action a1() { hdr.o.h1 = h_ieee.get({hdr.ipv4.src, hdr.tcp.dport}); }
  action a2() { hdr.o.h2 = h_p1.get({hdr.ipv4.src, hdr.tcp.dport}); }
  action a3() { hdr.o.h3 = h_p2.get({hdr.ipv4.src, hdr.tcp.dport}); }
  action a4() { hdr.o.h4 = h_p3.get({hdr.ipv4.src, hdr.tcp.dport}); }
  action a5() { hdr.o.h5 = h_p4.get({hdr.ipv4.src, hdr.tcp.dport}); }
  action a6() { hdr.o.h6 = h_p5.get({hdr.ipv4.src, hdr.tcp.dport}); }
  action a7() { hdr.o.h7 = h_p6.get({hdr.ipv4.src, hdr.tcp.dport}); }
  action a8() { hdr.o.h8 = h_p7.get({hdr.ipv4.src, hdr.tcp.dport}); }
  action a9() { hdr.o.h9 = h_p8.get({hdr.ipv4.src, hdr.tcp.dport}); }
  action a10() { hdr.o.h10 = h_p9.get({hdr.ipv4.src, hdr.tcp.dport}); }
  action a11() { hdr.o.h11 = h_p10.get({hdr.ipv4.src, hdr.tcp.dport}); }
  action a12() { hdr.o.h12 = h_p11.get({hdr.ipv4.src, hdr.tcp.dport}); }
  action a13() { hdr.o.h13 = h_p12.get({hdr.ipv4.src, hdr.tcp.dport}); }
  action a14() { hdr.o.h14 = h_p13.get({hdr.ipv4.src, hdr.tcp.dport}); }
  action a15() { hdr.o.h15 = h_p14.get({hdr.ipv4.src, hdr.tcp.dport}); }
  action a16() { hdr.o.h16 = h_p15.get({hdr.ipv4.src, hdr.tcp.dport}); }
  action at0() { hdr.o.t0 = (bit<16>)h_t0.get({hdr.ipv4.src, hdr.tcp.dport}); }
  action at1() { hdr.o.t1 = (bit<16>)h_t1.get({hdr.ipv4.src, hdr.tcp.dport}); }
  action fin() { ig_tm_md.ucast_egress_port = ig_intr_md.ingress_port; ig_tm_md.bypass_egress = 1; }
  apply { a0(); a1(); a2(); a3(); a4(); a5(); a6(); a7(); a8(); a9(); a10(); a11(); a12(); a13(); a14(); a15(); a16(); at0(); at1(); fin(); }
}
parser EgParser(packet_in pkt, out headers_t hdr, out meta_t meta, out egress_intrinsic_metadata_t eg_intr_md) {
  state start { pkt.extract(eg_intr_md); transition accept; }
}
control Eg(inout headers_t hdr, inout meta_t meta, in egress_intrinsic_metadata_t eg_intr_md, in egress_intrinsic_metadata_from_parser_t eg_prsr_md,
           inout egress_intrinsic_metadata_for_deparser_t eg_dprsr_md, inout egress_intrinsic_metadata_for_output_port_t eg_oport_md) { apply {} }
control EgDeparser(packet_out pkt, inout headers_t hdr, in meta_t meta, in egress_intrinsic_metadata_for_deparser_t eg_dprsr_md) { apply { pkt.emit(hdr); } }
Pipeline(IgParser(), Ig(), IgDeparser(), EgParser(), Eg(), EgDeparser()) pipe;
Switch(pipe) main;
