#!/usr/bin/env python3
"""Generate crcpoly.p4 from the CRC32_BANK in dpdk-nfs/lib/util/crc32.h (see README.md)."""

import importlib.util
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent

spec = importlib.util.spec_from_file_location("crc32_polynomials", ROOT / "random_experiments" / "crc32_polynomials.py")
polynomials = importlib.util.module_from_spec(spec)
spec.loader.exec_module(polynomials)

KEY = "{hdr.ipv4.src, hdr.tcp.dport}"


def main() -> None:
    bank = polynomials.read_bank()
    n = len(bank)
    fields = " ".join(f"bit<32> h{i};" for i in range(n + 1)) + " bit<16> t0; bit<16> t1;"
    polys = "\n".join(
        f"  CRCPolynomial<bit<32>>(0x{c:08X}, {'true' if r else 'false'}, false, false, 0x{init:08X}, 0x{xor:08X}) p_{name};"
        for name, c, r, init, xor in bank
    )
    hashes = "  Hash<bit<32>>(HashAlgorithm_t.CRC32) h_builtin;\n"
    hashes += "\n".join(f"  Hash<bit<32>>(HashAlgorithm_t.CUSTOM, p_{name}) h_{name};" for name, *_ in bank)
    hashes += f"\n  Hash<bit<10>>(HashAlgorithm_t.CUSTOM, p_{bank[0][0]}) h_t0;\n  Hash<bit<10>>(HashAlgorithm_t.CUSTOM, p_{bank[1][0]}) h_t1;"
    actions = f"  action a0() {{ hdr.o.setValid(); hdr.o.h0 = h_builtin.get({KEY}); }}\n"
    actions += "\n".join(f"  action a{i + 1}() {{ hdr.o.h{i + 1} = h_{name}.get({KEY}); }}" for i, (name, *_) in enumerate(bank))
    actions += f"\n  action at0() {{ hdr.o.t0 = (bit<16>)h_t0.get({KEY}); }}\n  action at1() {{ hdr.o.t1 = (bit<16>)h_t1.get({KEY}); }}"
    calls = " ".join(f"a{i}();" for i in range(n + 1)) + " at0(); at1();"

    p4 = f"""// GENERATED by tofino/exp-hash/gen_crcpoly.py from dpdk-nfs/lib/util/crc32.h -- do not edit.
// Which software CRC does each CRCPolynomial configuration of the bank compute? The built-in CRC32
// plus every bank entry hash {{ipv4.src, tcp.dport}}; the 32-bit results and two 10-bit truncations
// are appended to the packet, which loops back to its ingress port. See README.md.
#include <core.p4>
#include <t2na.p4>
header ethernet_h {{ bit<48> dst; bit<48> src; bit<16> etype; }}
header ipv4_h {{ bit<8> vihl; bit<8> tos; bit<16> len; bit<16> id; bit<16> frag; bit<8> ttl; bit<8> proto; bit<16> csum; bit<32> src; bit<32> dst; }}
header tcp_h {{ bit<16> sport; bit<16> dport; bit<32> seq; bit<16> data3; bit<16> win; }}
header out_h {{ {fields} }}
struct headers_t {{ ethernet_h eth; ipv4_h ipv4; tcp_h tcp; out_h o; }}
struct meta_t {{ }}
parser IgParser(packet_in pkt, out headers_t hdr, out meta_t meta, out ingress_intrinsic_metadata_t ig_intr_md) {{
  state start {{ pkt.extract(ig_intr_md); pkt.advance(PORT_METADATA_SIZE); pkt.extract(hdr.eth); pkt.extract(hdr.ipv4); pkt.extract(hdr.tcp); transition accept; }}
}}
control IgDeparser(packet_out pkt, inout headers_t hdr, in meta_t meta, in ingress_intrinsic_metadata_for_deparser_t ig_dprsr_md) {{ apply {{ pkt.emit(hdr); }} }}
control Ig(inout headers_t hdr, inout meta_t meta, in ingress_intrinsic_metadata_t ig_intr_md, in ingress_intrinsic_metadata_from_parser_t ig_prsr_md,
           inout ingress_intrinsic_metadata_for_deparser_t ig_dprsr_md, inout ingress_intrinsic_metadata_for_tm_t ig_tm_md) {{
  // coeff, reversed, msb, extended, init, xor
{polys}
{hashes}
{actions}
  action fin() {{ ig_tm_md.ucast_egress_port = ig_intr_md.ingress_port; ig_tm_md.bypass_egress = 1; }}
  apply {{ {calls} fin(); }}
}}
parser EgParser(packet_in pkt, out headers_t hdr, out meta_t meta, out egress_intrinsic_metadata_t eg_intr_md) {{
  state start {{ pkt.extract(eg_intr_md); transition accept; }}
}}
control Eg(inout headers_t hdr, inout meta_t meta, in egress_intrinsic_metadata_t eg_intr_md, in egress_intrinsic_metadata_from_parser_t eg_prsr_md,
           inout egress_intrinsic_metadata_for_deparser_t eg_dprsr_md, inout egress_intrinsic_metadata_for_output_port_t eg_oport_md) {{ apply {{}} }}
control EgDeparser(packet_out pkt, inout headers_t hdr, in meta_t meta, in egress_intrinsic_metadata_for_deparser_t eg_dprsr_md) {{ apply {{ pkt.emit(hdr); }} }}
Pipeline(IgParser(), Ig(), IgDeparser(), EgParser(), Eg(), EgDeparser()) pipe;
Switch(pipe) main;
"""
    (HERE / "crcpoly.p4").write_text(p4)
    print(f"crcpoly.p4: built-in CRC32 + {n} bank entries")


if __name__ == "__main__":
    main()
